### ISSUE TITLE
ionic2: bulding for production error

### ISSUE THREAD

**Issue by thom7kick** [nogorilla/angular-cc-library#7]
```
[23:52:21]  build prod failed: Unexpected value 'CreditCardDirectivesModule' imported by the module 'AppModule' 
[23:52:21]  ionic-app-script task: "build" 
[23:52:21]  Error: Unexpected value 'CreditCardDirectivesModule' imported by the module 'AppModule' 
Error: Unexpected value 'CreditCardDirectivesModule' imported by the module 'AppModule'
    at /Users/thomas/Documents/thomas/projects/ionic/ionic2/LiloTime/node_modules/@angular/compiler/bundles/compiler.umd.js:14675:33
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/thomas/Documents/thomas/projects/ionic/ionic2/LiloTime/node_modules/@angular/compiler/bundles/compiler.umd.js:14660:51)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/thomas/Documents/thomas/projects/ionic/ionic2/LiloTime/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/thomas/Documents/thomas/projects/ionic/ionic2/LiloTime/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/thomas/Documents/thomas/projects/ionic/ionic2/LiloTime/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/thomas/Documents/thomas/projects/ionic/ionic2/LiloTime/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
    at analyzeNgModules (/Users/thomas/Documents/thomas/projects/ionic/ionic2/LiloTime/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (/Users/thomas/Documents/thomas/projects/ionic/ionic2/LiloTime/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)


```

**Comment by thekip** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
